platform :ios, '9.0'
use_frameworks!

target 'NhaTro' do

    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON'
    pod 'IQKeyboardManager'
    pod 'Firebase/Core'
    pod 'Firebase/Crash'
    pod 'Firebase/Messaging'
    pod 'FacebookCore', '~> 0.2'
    pod 'FacebookLogin', '~> 0.2'
    pod 'FacebookShare', '~> 0.2'
    pod 'FBSDKCoreKit', '~> 4.22.1'
    pod 'FBSDKLoginKit', '~> 4.22.1'
    pod 'FBSDKShareKit', '~> 4.22.1'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'NVActivityIndicatorView'
    pod 'Kingfisher', '~> 3.0'


end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end