platform :ios, ‘9.1’
use_frameworks!

target 'NhaTro' do

    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON'
    pod 'Bolts'
    pod 'IQKeyboardManager'
    pod 'Firebase/Core’
    pod 'Firebase/Crash'
    pod 'Firebase/Messaging'
    pod 'FacebookCore', '~> 0.2'
    pod 'FacebookLogin', '~> 0.2'
    pod 'FacebookShare', '~> 0.2'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'NVActivityIndicatorView'
    pod 'Kingfisher'
    pod 'NKVPhonePicker'
    pod 'GoogleSignIn'
    pod "TLPhotoPicker"
    pod 'GoogleMaps’
    pod 'GooglePlaces'
    pod "KRPullLoader"
	pod 'Viewer'

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['Texture', 'FacebookCore', 'FacebookLogin', 'FacebookShare', 'FBSDKCoreKit', 'FBSDKLoginKit', 'FBSDKShareKit', 'Bolts'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
